apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployname }}-svc
spec:
  selector:
    app: {{ .Values.deployname }}
  ports:
    - protocol: TCP
      port: {{ .Values.svcport }}
      targetPort: {{ .Values.port }}

